plugins {
    id 'java'
    id 'application'
}

group = 'ru.mipt.bit'
version = '1.0-SNAPSHOT'

application {
    mainClass = 'ru.mipt.bit.platformer.GameDesktopLauncher'
}

sourceCompatibility = 1.17
targetCompatibility = 1.17

repositories {
    mavenCentral()
    maven { url 'https://repo1.maven.org/maven2' }
}

dependencies {
    implementation "com.badlogicgames.gdx:gdx:1.11.0"
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:1.11.0"
    implementation "com.badlogicgames.gdx:gdx-platform:1.11.0:natives-desktop"

    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.2'
    testImplementation 'org.mockito:mockito-core:4.6.1'
    testImplementation 'org.mockito:mockito-junit-jupiter:4.6.1'

    // Для работы с временными файлами в тестах
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
        showStandardStreams = true
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
